name: CI healthz check pr

on: 
  pull_request:
    branches: [main]

jobs:
  test:
    name: test cases check
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DB_USERNAME }}
      PASSWORD: ${{ secrets.DB_PASSWORD }}
      HOST: ${{ secrets.DB_HOST }}
      PORT: ${{ secrets.DB_PORT }} 
      APPORT: ${{ secrets.PORT }} 
      DATABASE: ${{ secrets.DB_NAME}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PostgreSQL
      run: |
        sudo apt update
        sudo apt install -y postgresql postgresql-contrib
        sudo systemctl start postgresql

    - name: Set up Node.js using GitHub Action
      uses: actions/setup-node@v3
    
    - name: Install node modules
      run: npm i

      
    - name: Set up PostgreSQL user and database
      run: |
        sudo -i -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h localhost -U postgres -c "CREATE DATABASE ${{ secrets.DB_NAME }};"

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_isready -h localhost -U postgres && break
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
    
    - name: Run tests
      run: npm test