name: Healthz pr Packer test

on: 
    pull_request:
        branches: [main]

env:
  PRODUCT_VERSION: "1.12.0"  # packer version app using

jobs:
    packer-test:
        runs-on: ubuntu-latest

        steps:
        - name: Check the Repo
          uses: actions/checkout@v3
        
        - name: Setup packer
          uses: hashicorp/setup-packer@main
          with:
            version: ${{ env.PRODUCT_VERSION }}
        
        - name: Intializing Packer
          working-directory: packer
          run: packer init healthz-mi.pkr.hcl

        - name: Formatting Packer
          working-directory: packer
          run: packer fmt healthz-mi.pkr.hcl

        - name: validate Packer
          working-directory: packer
          run: packer validate healthz-mi.pkr.hcl
        