name: Node.js Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install PostgreSQL
        run: |
          echo "Installing PostgreSQL"
          sudo apt-get update -y
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Configure PostgreSQL without systemd
        run: |
          echo "Starting PostgreSQL manually"
          sudo service postgresql start

      - name: Update database password
        run: |
          echo "Updating database password"
          sudo -u postgres psql -c "ALTER USER ${{secrets.DB_USERNAME}} WITH PASSWORD '${{secrets.DB_PASSWORD}}';"

      - name: Run tests
        run: npm test 

      - name: Success notification
        if: success()
        run: |
          echo "All tests passed!" > $GITHUB_STEP_SUMMARY
          echo "This PR can now be merged!" >> $GITHUB_STEP_SUMMARY